usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /

venta:
    resource: "@VentaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
